### ISSUE TITLE
Number of comparisons for five elements

### ISSUE THREAD

**Issue by tomdalling** [PunkChameleon/ford-johnson-merge-insertion-sort#1]
How many comparisons does this implementation take for the input `[8, 5, 6, 7, 1]`? 

I have an implementation that requires 8 comparisons, but I'm lead to believe that [the maximum should be 7](https://oeis.org/A001768). I tested all permutations of the input, and 32/120 require 8 comparisons, with the rest requiring 7 or less. It's driving me crazy. I did a pen-and-paper run through, and that also gave me 8 comparisons.

This is my working out:

1. Split into pairs, with remainder:  
   `[8,5] [6,7] [1]`
1. Sort inside pairs (2 comparisons):  
   `[5,8] [6,7] [1]` (compares `5<=>8` and `6<=>7`)
1. Recursively sort greater half of pairs (1 comparison):  
   `[6,7] [5,8] [1]` (compares `7<=>8`)
1. Split into two chains---the "main chain" S, and the rest, leaving remainder: 
   `[7,8] [6,5] [1]`
1. Move across the lesser half of the first pair:
   `[6,7,8] [5] [1]`
1. Binary insertion sort the last lesser half (2 comparisons):
   `[5,6,7,8] [1]` (compares `5<=>7` then `5<=>6`)
1. Binary insertion sort the remaining "odd" value (3 comparisons):
   `[1,5,6,7,8]` (compares `1<=>7` then `1<=>6` then `1<=>5`)
1. Total comparisons: 2 + 1 + 2 + 3 = 8

I feel like something might be wrong with the insertion part.

**Comment by CodeOptimist** [comment]
I am not @PunkChameleon but there are a couple bugs in this code. I solved them but haven't had time to submit a pull request yet. I also took the Clojure implementation, took the entire raw JavaScript code that "is" Clojure, put it in a massive file with working test code, converted it to Python with Js2Py, and then wrote a metaprogram to slowly reduce it from 48,000 lines of code to 4,700 lines of code. It works perfectly, but is quite slow (still much faster than human comparison and thus fulfills its purpose as-is).

Still, I would like to step through it in a debugger and use it to correct @PunkChameleon's implementation here, as when I gave it a comparator, and recorded how many times that comparator was _actually_ uniquely executed (I cached results and also their inverse) it's well over twice as many comparisons as my clojure-converted version. Which seems to make this code broken as-is even with my bugfixes.

It may be (probably is?) something extraordinarily simple but I haven't had time to study them enough yet. However this project is of incredible use to me so if I'm able to fix this one I will fork it / pull request it. I have had implementing this reliably in Python the back-burner for a year or so now, I was shocked and delighted to find someone put so much work in.

Maybe my bugfixes can be of help here. I will try to get them submitted.

**Comment by tomdalling** [comment]
Interesting, @CodeOptimist! Thanks for the info. Are you talking about this Clojure implementation? https://github.com/decidedlyso/merge-insertion-sort . Maybe @decidedlyso can weigh in.

**Comment by CodeOptimist** [comment]
Yes that's it! It worked excellently for me. As Clojure code in my web browser and as an automatically converted Clojure->Python abomination.

**Comment by CodeOptimist** [comment]
[decidedlyso_fjmi.zip](https://github.com/PunkChameleon/ford-johnson-merge-insertion-sort/files/5412402/decidedlyso_fjmi.zip)
Here you go. Go crazy. See last four lines for usage. Also reproduced here:

```python
import random
random_list = [random.randint(0, 5000) for i in range(100)]
cj_sorted = fjmi['cljs']['core'].to_array(fjmi['merge_insertion_sort']['core'].sort(lambda a, b: a < b, random_list)).to_list()
assert cj_sorted == sorted(random_list)
```

You can feed these Js2Py functions raw Python lists and such and it is smart enough to make them its weird Js "arrays" or whatever... so it just works.

I need a ~250 line implementation like @PunkChameleon 's though 😂.

**Comment by tomdalling** [comment]
I know what my bug was now, after looking at the diagrams in the Clojure implementation's repo.

Step 4 (split into two chains) should be `[7,8] [6,5,1]`, not `[7,8] [6,5] [1]`. The "odd" value needs to be appended to the lesser chain, because it affects the insertion order. I was inserting `5` and then `1`, when I was supposed to be inserting `1` and then `5`.

The difference is:

1. insert `5` into `[6,7,8]` takes a maximum of 2 comparisons
1. insert `1` into `[5,6,7,8]` takes a maximum of **3 comparisons**

vs

1. insert `1` into `[6,7,8]` takes a maximum of 2 comparisons
1. insert `5` into `[1,6,7,8]` takes a maximum of **2 comparisons**, because it's not possible for it to be inserted past the `8`, so it's actually being inserted into the sequence `[1,6,7]`.

All my tests pass now, including checking the upper limit of comparisons, so I think I'm done. The implementation is in Ruby though, so I don't have a PR for this repo unfortunately.

Thanks for the help @CodeOptimist !

**Comment by PunkChameleon** [comment]
@CodeOptimist @tomdalling so happy to hear this repo is being of some use to you guys!

@CodeOptimist - would **love** to merge in any optimizations and fixes you find when you get a chance. Having a method to more properly cache and test the comparators would be great too (like you described) - felt like my testing scripts didn't get that deep and would have definitely benefited from that as well.

Thanks again, and love that you both are diving into this code and it's proving helpful in some way!

**Comment by tomdalling** [comment]
As an update, I threw away my first implementation and started again from scratch. The result is here: https://github.com/tomdalling/ford_johnson/blob/main/lib/ford_johnson.rb . The functions don't really match up with this Python version so it's hard to say what could be copied across, but now that I understand the algorithm I'm happy to answer any questions. I've put a lot of comments into the source code too.
